import pygame as pg

BLACK = pg.Color(0, 0, 0)
GREY = pg.Color(32, 32, 32)
WHITE = pg.Color(255, 255, 255)
RED = pg.Color(255, 0, 0)

DIFFICULTY_PRESETS = [
    {
        "INPUT_DERIVATIVE": 1,
        "ENEMY_WAIT": 1024,
        "ENEMY_SPEED": 256,
        "ENEMY_ADD_SPEED": 16,
        "LATENCY_FACTOR": 1000,
        "BALL_ACTION_FORCE": 1000,
        "BALL_FRICTION": 10,
        },
    {
        "INPUT_DERIVATIVE": 2,
        "ENEMY_WAIT": 2048,
        "ENEMY_SPEED": 32,
        "ENEMY_ADD_SPEED": 16,
        "LATENCY_FACTOR": 1,
        "BALL_ACTION_FORCE": 1000,
        "BALL_FRICTION": 10,
        },
    {
        "INPUT_DERIVATIVE": 2,
        "ENEMY_WAIT": 2048,
        "ENEMY_SPEED": 0,
        "ENEMY_ADD_SPEED": 0,
        "LATENCY_FACTOR": 1,
        "BALL_ACTION_FORCE": 8000,
        "BALL_FRICTION": 40,
        },
    ]
DIFFICULTY_SELECTED = 1

FPS = 60
N_PHYSICS_SUBSTEPS = 10
INPUT_DERIVATIVE = DIFFICULTY_PRESETS[DIFFICULTY_SELECTED]["INPUT_DERIVATIVE"]

CAM_DAMPING_FACTOR = 10
BORDER_S_WIDTH = 1 / 4

BALL_RADIUS = 20
BALL_ACTION_FORCE = DIFFICULTY_PRESETS[DIFFICULTY_SELECTED]["BALL_ACTION_FORCE"]
BALL_RESTITUTION = 0.75
BALL_FRICTION = DIFFICULTY_PRESETS[DIFFICULTY_SELECTED]["BALL_FRICTION"]

LATENCY_FACTOR = DIFFICULTY_PRESETS[DIFFICULTY_SELECTED]["LATENCY_FACTOR"]

ENEMY_WAIT = DIFFICULTY_PRESETS[DIFFICULTY_SELECTED]["ENEMY_WAIT"]
ENEMY_SPEED = DIFFICULTY_PRESETS[DIFFICULTY_SELECTED]["ENEMY_SPEED"] / FPS
ENEMY_ADD_SPEED = DIFFICULTY_PRESETS[DIFFICULTY_SELECTED]["ENEMY_ADD_SPEED"] / FPS

BOUND_OBST_WIDTH = 32, 256
BOUND_OBST_HEIGHT = BALL_RADIUS * 4, BALL_RADIUS * 16
BOUND_OBST_DIST = BOUND_OBST_WIDTH[1] + BALL_RADIUS * 4, 1024
MAX_N_OBSTS = 16

DEBUG = False
FULL_SCREEN = True

if DEBUG:
    FULL_SCREEN = False
